### ISSUE TITLE
Add Machine Learning

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#1]
The term "Machine Learning" should be added to DRAO. This item has been brought over from https://github.com/FAIRsharing/subject-ontology/issues/3 . Definition, IRI to follow.

**Comment by Drosophilic** [comment]
I'll add a definition in the next round.

**Comment by Drosophilic** [comment]
I haven't had time to do this, @allysonlister, would you like to have a go.
