### ISSUE TITLE
Genomic Variation

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#12]
https://fairsharing.org/biodbcore-001182 has requested this term. Could be inserted via VariO into DRAO (https://www.ebi.ac.uk/ols/ontologies/vario/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVariO_0131). However, as we cannot use the native VariO hierarchy, existing VariO terms (specifically 'chromatin structure variation') have been placed within the SO sequence_collection hierarchy. We may wish to revisit this placement prior to adding genomic variation, if we decide to add this term.

**Comment by Drosophilic** [comment]
Genomic Variation could be captured in other ways (e.g. 'Genetic polymorphism').
I think we need to discuss this at the next call.

**Comment by Drosophilic** [comment]
I think we can remove this term. I have added SNPs to the record as this more accurately captures the domain.
