### ISSUE TITLE
November: Possible additions to DRAO likely to stay as user-defined tags

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#13]
Users have requested the following terms. None exist in OLS / Ontobee, and as such would require the minting of a new URI if we went forward with the term. As this is an application ontology, I think such things should only happen for particularly high-frequency user-defined tags. Therefore it is my recommendation that the following remain as user-defined terms for now, but I would like confirmation from @Drosophilic please.

* 'Proteome annotation' (https://fairsharing.org/bsg-d001188). Similar DRAO terms: annotation, sequence annotation, genome annotation. I have added 'Proteome' and 'Sequence Annotation' to the record.
* 'Protein Homology' (https://fairsharing.org/bsg-d001188). Similar OLS terms: 'protein structural homology' (but not identical). Similar DRAO terms: 'homologous'. I have added 'Homologous' to the record.
* Systems toxicology (https://fairsharing.org/FAIRsharing.h3tjtr): Similar DRAO terms: Toxicology and Systems biology (both already present in record).
* Adverse outcome pathways (https://fairsharing.org/FAIRsharing.h3tjtr): Similar DRAO terms: Adverse effect, adverse reaction. Similar OLS terms: adverse event outcome. Added 'Adverse reaction' to record.
* Circadian biology (https://fairsharing.org/biodbcore-001170/): Not sure what an appropriate alternative to this would be - chronobiology (https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0026517) and move to SRAO, or something else?
* Allosteric signalling map (https://fairsharing.org/biodbcore-001167/). Retain as user-defined tag.

The following may not have a wide-enough user base to be added to DRAO (this is what we need to decide in this ticket), but do have equivalent classes in OLS / Ontobee:

* Snow (https://fairsharing.org/biodbcore-001178/): Matching OLS term: Snow (https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_01000406)
* Permafrost (https://fairsharing.org/biodbcore-001178/): Matching OLS term: Permafrost (https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000134)
* Biological rhythms (https://fairsharing.org/biodbcore-001170/): Near match in OLS: Circadian rhythms (https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007623)
* Protein translocation (https://fairsharing.org/biodbcore-001186/): There are some near matches in OLS which we could choose from with a little digging, but not sure it's worth the effort to upgrade to DRAO at this time.
* Allosteric regulation (https://fairsharing.org/biodbcore-001167/): Matching OLS term is https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0001913

**Comment by allysonlister** [comment]
I have updated this ticket with a number of new terms for consideration, and this should be reviewed when convenient.

**Comment by Drosophilic** [comment]
Hi @allysonlister, I agree with your opinion that we should mint new URIs very rarely. 

All the terms in the first list appear to be composite terms, and can in most cases be captured via existing terms.

I think that all on the second list should remain as user tags for now (and I'm not sure circadian rhythms is close enough to biological rhythms).

**Comment by allysonlister** [comment]
Thanks very much @Drosophilic - as a final note before I close this, should I remove the tags in the first list, as we have appropriate terms already, or shall we leave them as user-defined terms for now? I would lean towards the latter, but happy either way.

Thanks :) Ally

**Comment by Drosophilic** [comment]
I would also lead towards the latter (keeping them as user-defined terms). Thanks!
