### ISSUE TITLE
Protein complex

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#15]
Requested by Complex Portal (https://fairsharing.org/biodbcore-001173/). We have variants on this term, but not the term itself. Considering its wide applicability, it would be good to include it in DRAO.

We would have many choices in our external ontologies, though GO might be best (protein-containing complex, https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0032991)

**Comment by Drosophilic** [comment]
The GO term sounds appropriate, although I'm not sure about keeping 'Protein Complex' as a synonym.

**Comment by allysonlister** [comment]
Ok - I'll proceed with this, but not retain the user suggestion of _Protein complex_, and just retaining the GO label and other annotation.

**Comment by allysonlister** [comment]
Note: This class was already in DRAO, just invisible to the user. Have made it visible now.

**Comment by allysonlister** [comment]
Please note that GO has 'protein complex' as a narrow synonym and therefore this synonym has been retained in DRAO.
