### ISSUE TITLE
Amino Acid Sequence versus Protein Sequence

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#17]
In the past we have had both tags. In the current version of DRAO we have put them together as synonyms, as this is what most ontologies in OLS do. I would just like to check that we 

1. are happy with this, and
2. Are happy with having 'amino acid sequence' as the primary label, and 'protein sequence' as an alternative label.

**Comment by Drosophilic** [comment]
I guess so. I think there are differences (primary versus secondary) but for brevity lets combine them, with 'amino acid sequence' as the primary label. Thanks.
