### ISSUE TITLE
Sample Annotation

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#18]
'Sample Annotation' is currently a synonym of the FAIRsharing term 'Biological Sample Annotation' because we have sourced this term from EDAM (data_3113). In the next update I suggest we either

1. change this source to either mint our own term or find another (though no other suitable one exists - with a quick search - in OLS), or
2. Remove the original label from the import from EDAM as it is confusing - we are broader in scope than just biology, and the definition from EDAM ("Annotation on a biological sample, for example experimental factors and their values.") makes it clear that they only mean biological samples.

**Comment by Drosophilic** [comment]
I think option 2 is the cleanest. Thanks.

**Comment by allysonlister** [comment]
This is less straightforward than I'd like, as I don't want to have this removal of the rdfs:label become a manual step. I think it may be possible to do with Robot, but need to look into it. If the solution drags a bit, I may push this to the next release.
