### ISSUE TITLE
Disease

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#19]
Currently, 'disease' is present within DRAO but is not visible to FAIRsharing users as it does not have the inSubset annotation. I have applied the URI http://www.ebi.ac.uk/efo/EFO_0000408 to the FAIRsharing site as this is the one used within DRAO, but we will have to 'enable' this class to make it visible to users.

**Comment by Drosophilic** [comment]
I've noticed the synonyms in EFO include Human Disease. Are we importing that across? It wouldn't make sense to do so as some disease will (of course) not be human. Importing that synonym would create inaccuracies, particularly in the search.

**Comment by allysonlister** [comment]
Thanks for noticing that @Drosophilic - we could use the OGMS term which has a suitable definition and matching position within the BFO hierarchy (see http://purl.obolibrary.org/obo/OGMS_0000031, and https://www.ebi.ac.uk/ols/ontologies/ogms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOGMS_0000031) without the downsides of the EFO synonyms. 

Would this be preferrably?

**Comment by Drosophilic** [comment]
Personally, the OGMS term seems to fit best.
