### ISSUE TITLE
Liver disease

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#2]
A user has requested "Liver disease". We already have "Liver" (UBERON_0002107) and disease (EFO_0000408). However, it makes sense to add "Liver disease" (http://purl.obolibrary.org/obo/DOID_409) as we already have "kidney disease" and "bone disease", both already sourced from DOID. Are we in agreement?

**Comment by agbeltran** [comment]
Sounds good to me.
