### ISSUE TITLE
Material processing

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#20]
Currently we have the OBI term 'Material processing' with a FAIRsharing alternative term of 'Bioprocessing'. This isn't strictly accurate, as the definition of the OBI term is generic and not specific to items of biological origins. We might wish to create a child term that has a specific biological relevance. However, no such term exists in OLS so we would need to mint one if we wanted to do this.

**Comment by Drosophilic** [comment]
Remove 'Bioprocessing' as a visible term as other terms are sufficient.
