### ISSUE TITLE
Neuroimaging (measurement)

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#21]
Currently we have an invisible hierarchy class ('Neuroimaging') from OMIT and sitting in its MeSH_term hierarchy. We also have the visible class 'Neuroimaging measurement' (with a already-existing FAIRsharing label of 'Neuroimaging') from EFO. I would like to 

1. move the visible child term ('Diffusion Tensor Imaging') from its existing location as a child of the OMIT 'Neuroimaging' to become a child of 'Neuroimaging measurement', and
2. This would cause the automatic removal of the OMIT 'Neuroimaging' term.

We may optionally wish to add an alternative term of 'Brain imaging' to this class.

This would be a lot cleaner.

**Comment by Drosophilic** [comment]
Agreed. However, this does not take into account that Brain imaging is only a subset of NeuroImaging. See linked ticket where we set out to resolve this.
