### ISSUE TITLE
Mesh hierarchy issues

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#33]
At the moment, we have a significant number of mesh terms in DRAO. These terms are, in themselves, good. However they bring with them the Mesh hierarchy which creates a duplicated / parallel hierarchy within DRAO. Additionally, although the main hierarchy for each of the leaf terms is not visible to our users, the labels for these hierarchies can be confusing if we ever wish to expose the hierarchies of DRAO to aid searching, for example. I think we need to
![mesh](https://user-images.githubusercontent.com/143586/51678407-39842480-1fd4-11e9-9595-db0c6231b82d.png)
I think we need to

1. Go through those terms originating from Mesh, which themselves are being important from various external ontologies. 
2. Look for ones that have sensible alternatives and use them
3. Those which cannot be refactored must change their hierarchy via the Ontofox configuration file.

The ultimate goal would be to remove the Mesh hierarchy from DRAO to have an integrated hierarchy for our domain tags.

**Comment by allysonlister** [comment]
* Laboratory Automation: 1 hidden record - make child of OBI technique
* Crowdsourcing: 5 records - child of planned process or perhaps experimental process
* Electronic Health Records - 15 records - child of clinical data item, but change from OMIT to NCIT (http://purl.obolibrary.org/obo/NCIT_C142529) which has a definition.
* Benchmarking - one record - child of EDAM Analysis (which is a child of, ultimately, data transformation)
* Reproducibility of Results - 1 record - change to http://purl.obolibrary.org/obo/NCIT_C15318 for definition ("Reproducibility") - either child of EDAM report or child of OBO data item
* Breeding - 15 records. We need to delete this in favor of the SRAO terms Animal Breeding and Plant Breeding. So, recurate the 15 records then delete this term.
* High-Throughput Screening Assays - 1 record - change to High Throughput Screening http://purl.obolibrary.org/obo/NCIT_C18472 as has definition. Child of assay

This comment will be updated with the rest of the terms as I work through them.

**Comment by allysonlister** [comment]
Notes on the changes:
* Reproducibility has been placed as a child of qualitative, as it is a quality of data and the NCIT page classed it as a qualitative concept (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C15318).

**Comment by allysonlister** [comment]
@Drosophilic - please could you confirm if you'd like Population dynamics as a part of DRAO (as it currently stands) or SRAO? Thanks!

**Comment by Drosophilic** [comment]
Thanks Ally.

- Would you like Population dynamics as a part of DRAO (as it currently stands) or SRAO?
Should it not be part of SRAO?

- thermodynamics - 4 records - Do you want to keep this? If so, we should move to SRAO and use http://purl.obolibrary.org/obo/NCIT_C17193.

Yes. We should move to SRAO.

- There is an empty "STATO alternative term" in the allele frequency class (see http://www.ontobee.org/ontology/STATO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000254). Would you like me to make an issue? I'm sure in a previous version it had an alternative term as gene frequency, or I wouldn't have written what I wrote in the checklist above about it being a suitable equivalence for gene frequency.

Yes. Please make an issue.

**Comment by allysonlister** [comment]
Great thanks - will add two to SRAO, and create an issue for STATO.

**Comment by allysonlister** [comment]
Please see https://github.com/ISA-tools/stato/issues/80 for the STATO issue related to this.

**Comment by allysonlister** [comment]
STATO are happy to add gene frequency with the next release (as an alternative term). Therefore I will go ahead with removing the OMIT gene frequency term. There is only one record annotated with this term (bsg-d000004) and the term "allele frequency" is appropriate, so I have updated the curation on that record and deletion of the OMIT term can proceed.

**Comment by allysonlister** [comment]
It seems that, due to the forest that was the MeSH hierarchy, I missed out a final few OMIT terms that were lurking within. The following should be the final hierarchy / refactoring changes required by this ticket:

- [ ]  Regenerative Medicine (http://purl.obolibrary.org/obo/OMIT_0023533) - 1 record. I suggest moving to SRAO and refactoring to NCIT (http://purl.obolibrary.org/obo/NCIT_C93254) as it has a suitable definition. Make a child of Medicine.
- [ ]  Electrophysiology (http://purl.obolibrary.org/obo/OMIT_0005842) - 6 records. I suggest moving to SRAO and refactoring to NCIT (http://purl.obolibrary.org/obo/NCIT_C16540) as it has a suitable definition. Make a child of Physiology.
- [ ]  Teaching material (http://purl.obolibrary.org/obo/OMIT_0014521) - 7 records. I suggest retaining this in DRAO, but becoming a child of IAO document ("A collection of information content entities intended to be understood together as a whole") instead.
- [ ] Workflow (http://purl.obolibrary.org/obo/OMIT_0026906) - 5 records. Retain in DRAO, but refactor to http://purl.obolibrary.org/obo/NCIT_C42753 for the definition and make a child of IAO plan specification. 
- [ ] Genetic Phenomena (http://purl.obolibrary.org/obo/OMIT_0026382) - seems to be unused. If this is the case, I recommend removing it as it is a very vague term and we have lots of DRAO and SRAO terms relating to genes.
- [ ] Radiation (http://purl.obolibrary.org/obo/OMIT_0012758) - 1 record. Replace with http://purl.obolibrary.org/obo/ENVO_01001023 for hierarchy and definition.

Please can you confirm you are OK with these solutions @Drosophilic ? Thanks!

**Comment by Drosophilic** [comment]
These are all fine apart from 'Teaching Material', as some teaching material may be media e.g. video etc. I'm not sure where it should go though.

**Comment by allysonlister** [comment]
Yes, the "document" label is counter intuitive, which is why I put the definition in. In theory, document fits because the definition stipulates a collection of ICEs. However, the label ("document") is one that many people would interpret very differently from the stated definition.

Theoretically, I could see it as a role or quality - it could be any ICE that has the role of being teaching materials. Perhaps as a child of role then @Drosophilic ?

**Comment by Drosophilic** [comment]
I'm not sure users would understand 'teaching materials' to be a role, although I see the point your making. I wonder if there is anywhere else?

**Comment by allysonlister** [comment]
Otherwise, I would just suggest as a child of ICE, as multimedia / video etc are.

**Comment by allysonlister** [comment]
Cool - I shall interpret your thumbs up as approving of me placing it under ICE :)
