### ISSUE TITLE
Top-down Proteomics

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#4]
A user has added a new tag to called "Top-down Proteomics" (see https://fairsharing.org/bsg-s001213). Details of this methodology can be seen at https://en.wikipedia.org/wiki/Top-down_proteomics 

I suggest that we add this to DRAO. While we already have "Proteomics" as a discipline in SRAO, this seems to be a more technical experimental method, and seems better suited to DRAO.

Please note that PRIDE is currently not part of Ontobee (although it is present in OLS), and therefore this term would need to be added via manual rather than automatic imports.

Position: Child of "mass spectrometry assay" from OBI.
IRI: http://purl.obolibrary.org/obo/PRIDE_0000427
definition: Top-down Proteomics is a method of protein identification that uses an ion trapping mass spectrometer to store an isolated protein ion for mass measurement and tandem mass spectrometry analysis. Top-down proteomics is capable of identifying unique proteoforms (the specific molecular form of the protein resulting from combinations of genetic variation, alternative splicing, and post-translational modifications) through the analysis of intact proteins. Both the intact and fragment ions masses of a protein can be measured. This approach routinely allows for 100% sequence coverage and full characterization of proteoforms. The potential for achieving full protein characterization has made the Top Down mass spectrometry approach extremely useful for analysis of single proteins or simple mixtures of significant biological interest. [Adapted by AL from https://dx.doi.org/10.1016%2Fj.bbrc.2014.02.041 and Wikipedia (https://en.wikipedia.org/wiki/Top-down_proteomics), 5.6.18]

Please note that the PRIDE definition has not been retained, in favor of a FAIRsharing definition which is more detailed. 

Please can I have people's thoughts on:

1. Should we include at all?
2. Do you agree it belongs in DRAO?
3. Are you happy with the definition/IRI/position?

Thanks!

**Comment by Drosophilic** [comment]
Sounds good. Happy with all.
