### ISSUE TITLE
Documentation - reference ontology licensing

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#41]
We need to ensure that we are following the licenses of all of the reference ontologies used in DRAO. This will likely involve updates to README.md or an additional documentation page.

**Comment by allysonlister** [comment]
As there are so many licenses, I hesitate to also put them in the ontology file itself (e.g. in the ontology-wide annotations) but this may be a good idea. What do you think @Drosophilic ?

**Comment by allysonlister** [comment]
I have added them to https://github.com/FAIRsharing/domain-ontology/blob/master/LicensingCompliance.md and this ticket can be closed once we have @Drosophilic 's thoughts on if we need to put the info anywhere else. Please note that not all license info could be found for all ontologies.

**Comment by Drosophilic** [comment]
I think keeping them in the readme is enough for now.
