### ISSUE TITLE
Addition of Data Architecture, Analysis and Design

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#42]
As part of https://github.com/FAIRsharing/subject-ontology/issues/19, we are refactoring composite terms. It has come to our attention that this composite term (http://edamontology.org/topic_3365) should be in DRAO, not SRAO and should be refactored.

* Data analysis - http://purl.obolibrary.org/obo/ERO_0001309
* Data design
* Data Architecture

We will need to remove the EDAM topic completely, as it is a composite term, and find new IRIs. Please note that this will require mapping SRAO terms to DRAO ones within the next FAIRsharing release to retain existing annotation.

**Comment by allysonlister** [comment]
There is only 1 record with this tag and it seems that this tag isn't appropriate for the record anyway (see https://fairsharing.org/biodbcore-001282/). I suggest we remove it completely, as we have other tags that can be used instead. @Drosophilic what are your thoughts regarding this?

**Comment by Drosophilic** [comment]
Yes, that record annotation looks inappropriate. I'll remove it. I agree we should remove this tag.

**Comment by allysonlister** [comment]
Has been removed from SRAO already, and no longer being added to DRAO, so this can be closed. Thanks @Drosophilic for updating the annotation in the record.
