### ISSUE TITLE
Data Identity and Mapping

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#43]
Data Identity and Mapping is a term that needs to be split and then added to DRAO. It originated in SRAO, where it has been deleted. It should be added at the same time as it is removed from SRAO so that we don't lose the tag, which currently applies to 13 records in FAIRsharing (https://fairsharing.org/search/?q=data+identity+and+mapping&selected_facets=expanded_onto_disciplines_exact:Data%20Identity%20and%20Mapping). See also https://github.com/FAIRsharing/subject-ontology/issues/33

Within SRAO it was listed as http://edamontology.org/topic_3345 (with additional FAIRsharing definition of "The use of identifier schema to provide unambiguous identification of entities and records in a variety of locations, such as databases, repositories, journals and datasets. [PAM 28.02.2018]") but will need new IRIs to accommodate the split concept.

**Comment by allysonlister** [comment]
Within DRAO, we currently have:

* Identifier topic_0842 "A text token, number or something else which identifies an entity, but which may not be persistent (stable) or unique (the same identifier may identify multiple things)."
* Centrally registered identifier IAO_0000578 "An information content entity that consists of a CRID symbol and additional information about the CRID registry to which it belongs."

Would either of these be suitable replacements (with checks against the 13 FAIRsharing records of course) for the Data Identity part of the above term?

For the Mapping portion, 'Data Mapping' from NCIT (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C142485) is available. Within NCIT it is a child of data processing. Within DRAO we have 'data transformation' from OBI (synonym data processing). We could place Data Mapping under Data transformation.

A final choice is to not split the term, but to just move it as-is across to DRAO. Which would you prefer, @Drosophilic ?

**Comment by Drosophilic** [comment]
Let's not split the term (as I don't think any suggestion truly fits) and just move it across to DRAO for now. We can revisit this when we look at DRAO in more depth. Unless you have strong preferences for another solution?

**Comment by allysonlister** [comment]
Sounds good. Will move it across now.
