### ISSUE TITLE
Enzyme appearing twice in FAIRsharing editor

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#44]
We need to check and see if the following is an artifact of the FAIRsharing site or an issue with DRAO:
![enzyme](https://user-images.githubusercontent.com/143586/58952766-864ee780-878c-11e9-9b3c-2682abf92dd9.png)

**Comment by allysonlister** [comment]
The latter is OBI_0000427 and the former is the EDAM term topic_0821. Both have the inSubset = FAIRsharing annotation property, so one needs to be deleted. The EDAM term is a child of protein, and the OBI term is a child of material entity, as its definition includes both rna and protein. I am tempted to retain the OBI term, as some enzymes can be RNA (or should those have a separate term called ribozymes?)

Either way, we need to clean this up. How would you like to proceed @Drosophilic ?

**Comment by allysonlister** [comment]
Duplicate of #28

**Comment by Drosophilic** [comment]
Hi Ally, I think we should retain the OBI term, for the reason you outlined. Thanks.
