### ISSUE TITLE
EDAM Data and IAO Data Item

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#48]
We currently have both the EDAM Data hierarchy and the IAO data item hierarchy. It would be good to resolve these into a single hierarchy.

**Comment by allysonlister** [comment]
### What are you changing?
Removing EDAM Data class (http://edamontology.org/data_0006) as it is redundant with IAO http://purl.obolibrary.org/obo/IAO_0000027

### Why are you suggesting this change?

We should avoid redundancy. This naturally appears as part of the computationally-generated hierarchies, but should be cleaned where possible. The wide variety of locations that the children of EDAM Data belong in show that the EDAM Data hierarchy is a mixture of different concepts.

### Mapping
We will attempt to only refactor IRIs where necessary, and do most of this via reshuffled hierarchies.

The info in this section should be added to development/refactored-IRIs-current.txt 

Old IRI | New IRI | Note
------------ | ------------- | -------------
http://edamontology.org/data_0006 (Data) |  | Deleted. Not visible in FAIRsharing, so no re-curation required.
http://edamontology.org/data_0842 (Identifier)|| Deleted. Not visible in FAIRsharing, so no re-curation required.
http://edamontology.org/data_1916 (Alignment)|| Deleted. Not visible in FAIRsharing, so no re-curation required.
http://edamontology.org/operation_0292 (Sequence Alignment)|http://purl.obolibrary.org/obo/OBI_0002567 (Sequence alignment)| The EDAM term is visible in FAIRsharing, so we will need to refactor this IRI.
http://edamontology.org/data_2534 (Sequence attribute)||Delete. Children of this term will go to SO Sequence attribute (http://purl.obolibrary.org/obo/SO_0000400)
http://edamontology.org/data_1353 (Sequence motif)|http://purl.obolibrary.org/obo/SO_0001683 (Sequence motif)|Using the SO term with its hierarchy is a better solution for DRAO.
Sequence set (http://edamontology.org/data_0850) |Sequence collection (http://purl.obolibrary.org/obo/SO_0001260)| The SO term is already present, neither are visible in FAIRsharing.
Text data (http://edamontology.org/data_2526)|Document part (http://purl.obolibrary.org/obo/IAO_0000314)|Text data isn't visible in FAIRsharing.

### Hierarchy

IRI| Old Position | New Position | Note
------------ | ------------- | ------------- | ------------
Children of http://edamontology.org/data_0842 (Identifier) |EDAM Identifier hierarchy | IAO Identifier hierarchy (http://purl.obolibrary.org/obo/IAO_0020000)|
Children of http://edamontology.org/data_1916 (Alignment), of http://edamontology.org/operation_2451 (Sequence Comparison), and http://edamontology.org/operation_0292 (Sequence Alignment) |EDAM Alignment (operation and data) hierarchies | OBI Sequence alignment hierarchy (http://purl.obolibrary.org/obo/OBI_0002567)| We will need to add this OBI term, but it fits with the rest of the DRAO hierarchy better. This also resolves the issue we were facing with EDAM having two different classes with the same label - Sequence alignment is present in EDAM both within the data and operation hierarchies. We will move what we need to the OBI term (though I realize one class is using alignment as a noun, and one as a verb, I think our users will expect a single hierarchy.)
http://edamontology.org/data_1597 (Codon Usage Table)| EDAM Data|IAO Data Item|
Evidence|EDAM Data|IAO ICE|A few other ontolgies also have a term for Evidence. SIO puts it as an ultimate child of ICE. Data item is also a child of ICE, but I'm not sure that Evidence is a type of data. **Should Evidence be a child of ICE, or of data item?**
Experimental measurement (http://edamontology.org/data_3108)|EDAM Data| EFO Measurement (http://www.ebi.ac.uk/efo/EFO_0001444)|
EFO Measurement (http://www.ebi.ac.uk/efo/EFO_0001444)| child of ICE| Child of IAO Data item|This is a better place for Measurement.
CD Spectra (http://edamontology.org/data_0939) and Mass spectrum (http://edamontology.org/data_0943)| EDAM Experimental measurement|spectrum (http://purl.obolibrary.org/obo/CHMO_0000800)
Expression data (http://edamontology.org/data_2603) and children| EDAM Data| assay output (http://purl.obolibrary.org/obo/CHMO_0000793)
GO-term enrichment data (http://edamontology.org/data_3754)| EDAM Data | IAO Data Item|
Map (http://edamontology.org/data_1274)|EDAM Data|IAO Data Item|
Mathematical model (http://edamontology.org/data_0950)|EDAM Data|IAO ICE|A model is not really data, but will fit nicely as an ICE.
Molecular property (http://edamontology.org/data_2087)|EDAM Data|IAO Data item|
Reaction data (http://edamontology.org/data_2978)|EDAM Data|IAO Data Item|
Children of http://edamontology.org/data_2534 (Sequence attribute)|EDAM Data|SO Sequence attribute (http://purl.obolibrary.org/obo/SO_0000400)|
Sequence motif (http://edamontology.org/data_1353)|Replaced by SO Sequence motif||See IRI refactoring table above.
Children of Sequence set (http://edamontology.org/data_0850)|EDAM Data|SO Sequence collection (http://purl.obolibrary.org/obo/SO_0001260)
Sequence similarity (http://edamontology.org/data_1413)|EDAM Data|IAO Data item|I feel there might be a better place, but can't immediately see one, so putting it here for the moment.
Children of Text data (http://edamontology.org/data_2526)| EDAM Data|IAO document part (http://purl.obolibrary.org/obo/IAO_0000314)|There are many other document parts in this part of IAO, but no need to add them at the moment.

That's the list @Drosophilic and @delphinedauga - please let me know if you're ok with the above, or if you have any comments, and I'll get started on a PR and making the updates.

Thanks!

**Comment by Drosophilic** [comment]
This is a great summary @allysonlister, thanks.

In response to your question on Evidence, looking at the IAO hierarchy, I think it should go under ICE, rather than Data Item. @delphinedauga @allysonlister - do you agree?

**Comment by allysonlister** [comment]
Delphine is also happy with the suggested changes, and we will go with Evidence under ICE.

I will progress with the updates. Thanks!

**Comment by allysonlister** [comment]
I've made the updates listed in this ticket. Please might @delphinedauga and @Drosophilic check the owl file to ensure they are happy with these updates prior to the creation of the next point release. 

It's best to look at the merged file at https://github.com/FAIRsharing/domain-ontology/blob/master/development/DRAO-merged.owl

Thanks!

**Comment by delphinedauga** [comment]
I opened the merge file and checked mapping and hierarchy -> sounds good to me ! Thanks Ally !

**Comment by allysonlister** [comment]
As @delphinedauga has checked the work, this ticket can be closed and the point release built. Thanks!
