### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#51]
While this tag is intended to be a generic term describing the classification of objects, the current definition (EDAM) is life-sciences-specific. We may wish to refactor as our intent is more wide-reaching:

"Assign molecular sequences, structures or other biological data to a specific group or category according to qualities it shares with that group or category."

The current hierarchy is:

![classification](https://user-images.githubusercontent.com/143586/88680935-f0d98a00-d0e8-11ea-8648-28977e55b3e1.png)

**Comment by allysonlister** [comment]
We agree that we need to find another class that properly describes classification in the more general sense. I will have a look at the existing curation for classification to determine if we also want to keep this term with another label that is more suited to the definition.

**Comment by allysonlister** [comment]
We currently have [52](https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=classification&expanded_onto_disciplines=&user_defined_tags=&search_state=visible&selected_facets=expanded_onto_domains_exact:Classification) records in FAIRsharing with _Classification_. It is worth noting the following about these records:

* We also have a DRAO term _Taxonomic classification_, so in theory any usage of _Classification_ should not be in relation to species. In practice, we have quite a few with both of these terms, which is not incorrect, but leads me to the next point...
* Currently, _Taxonomic classification_ is in a separate hierarchy to _Classification_. At first glance I thought this was incorrect, but it turns out we have _Taxonomic classification_ as a child of _organism name_ (definition "The full name for a group of organisms, reflecting their biological classification and (usually) conforming to a standard nomenclature."). Therefore, rather than it being the research area concerned with species classification, it is the actual taxonomic classification of an organism:
![taxclass](https://user-images.githubusercontent.com/143586/88683259-80803800-d0eb-11ea-8b30-e72425909397.png)
* Within the 52 records, _Classification_ is being used in the following ways in addition to its use as taxonomic classification (concurrently with the taxonomic classification tag): classifying enzymes (ExplorEnz https://fairsharing.org/FAIRsharing.da6cny), classification in linguistics (https://fairsharing.org/bsg-s001241), drug classification (https://fairsharing.org/FAIRsharing.spjjv8), disease classification (https://fairsharing.org/FAIRsharing.85k1jm), and a number of other biological classifications (e.g. genes). So it's fair to say that it is being used generally, though mainly with the life sciences. Personally, after seeing the definition I have held back from annotating with it for non-biological classification resources (can't remember which), so I think it would be used more generally with a better fitting definition.

There are two points here:

1. Should _Taxonomic classification_ stay where it is? I think we can probably leave it as its location fits with its meaning. If instead you'd like me to look for a suitable class that would fit as a child of _Classification_, please let me know.
2. Refactor _Classification_ to one of these choices (there are a couple of other options, but I think these are the best two):
http://purl.obolibrary.org/obo/NCIT_C25161
![ncitclass](https://user-images.githubusercontent.com/143586/88684273-980bf080-d0ec-11ea-9e69-14473555cb4f.png)

The OMIT term http://purl.obolibrary.org/obo/OMIT_0004280, which is taken from MeSH with the definition "The systematic arrangement of entities in any field into categories classes based on common characteristics such as properties, morphology, subject matter, etc."
![omitclass](https://user-images.githubusercontent.com/143586/88684513-e02b1300-d0ec-11ea-91db-9390bdf7ffd3.png)

Of the two, I prefer the definition and the hierarchy of the OMIT term. What do you two think, @delphinedauga and @Drosophilic? Thanks!

**Comment by Drosophilic** [comment]
Hi Ally, I also prefer the OMIT term. I also think Taxonomic Classification should stay where it is.

**Comment by allysonlister** [comment]
Thanks @Drosophilic that's great! @delphinedauga what are your thoughts?

**Comment by allysonlister** [comment]
### What are you changing?
Refactoring the Classification class.

### Why are you suggesting this change?
The current definition does match the more generic label, nor does it match FAIRsharing's use of the term.

### Mapping
Add to `development/refactored-IRIs-current.txt`
`http://edamontology.org/operation_2990|http://purl.obolibrary.org/obo/OMIT_0004280`

### Label
**Recommendation**: Classification

**Reasoning**: OMIT label, and our existing label.

### IRI
**Recommendation**: http://purl.obolibrary.org/obo/OMIT_0004280
 
**Reasoning**: See discussion earlier in the ticket.

### Definition
The systematic arrangement of entities in any field into categories classes based on common characteristics such as properties, morphology, subject matter [Adapted from https://meshb.nlm.nih.gov/record/ui?ui=D002965, AL 5.8.2020]

### Hierarchy
**Recommendation**: Child of _data transformation_

**Reasoning**: We don't currently have a mesh hierarchy in FAIRsharing and classification is a type of data transformation. It was a child of EDAM _operation_ (which itself is a child of _data transformation_), so this places it in a similar location.
![datatran](https://user-images.githubusercontent.com/143586/89388697-4969e200-d6fc-11ea-9663-a1a48da68505.png)

**Comment by allysonlister** [comment]
Work complete on this ticket.
