### ISSUE TITLE
Promotion of user-defined tags in relation to COVID-19 work?

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#53]
This is a summary of the comments below, with links out to other tickets where required:

- [x] Adverse outcome pathways - not promoted
- [x] Approved drug #56 
- [x] Coronavirus - completed merging with COVID-19 tag
- [x] Drug Target - not promoted
- [x] Drug repositioning - #55 
- [x] Drug target in DNA network - not promoted
- [x] Drug-like compound - not promoted
- [x] Infectology / infectious disease #57 -  from this [SRAO ticket](https://github.com/FAIRsharing/subject-ontology/issues/49#issuecomment-626703517)

End summary.

In the rest of the current FAIRsharing user-defined tags, the ones that might have some relevance to the current set of COVID records are the following, for each of which I'll need a Y or N as to whether or not I "promote" them to DRAO/SRAO. If yes, I will create individual tickets and link them to this one. Please note these aren't necessarily in any of our COVID resources, just pulled from the user-defined tag list as likely terms that people may want. This is intended as a low-effort check to give priority to any terms that might get used more in the coming weeks.

1. Adverse outcome pathways
2. Approved drug: We already have 'drug' and 'fda approved drug'. If we want this, it could go in the same hierarchy within DRAO that 'fda approved drug' goes in.
3. Coronavirus: We currently have three records <https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=&expanded_onto_disciplines=&user_defined_tags=coronavirus&record_id=&miriam_id=&search_state=visible> with this tag - I think it should be replaced with COVID-19 and then this tag deleted.
4. Drug Target: we already have 'target' from SIO but this doesn't have a definition. The BAO 'target' <https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0003064> has a definition, In either case, whichever term we use, we need to override the label as 'target' is very generic. Should change it to something like 'molecular target' or 'biological target'. If we want Drug Target, we will need to mint our own IRI.
5. Drug repositioning: If we want this, OMIT <https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0027237> does have this term, but no definition - we could add one if required.
6. Drug target in DNA network: see #4, not sure we need to be this specific.
7. Drug-like compound 

Any other terms?

**Comment by Drosophilic** [comment]
Hi Ally, I assume with any promotion you will go back and reannotate those records with the user tag so they have the newly minted DRAO term, right? (or will that be a separate Trello ticket?) We have to make sure these things don't fall through the cracks.

It would be good to see if any of these are used in our COVID-19 related records (or if they should be), before we promote them, given our limited capacity at present.

Now on to the tags you've pulled out:

1. Adverse outcome pathways
I would say no. It seems too detailed.

2. Approved drug
Yes

3. Coronavirus
I agree, this shouldn't be a tag and should be replaced by the COVID19 user tag.

4. Drug Target
Unless there is a specific record-related need for this tag, I suggest we keep this as a user-defined tag.

5. Drug repositioning
If this is attached to a record, I suggest we add it.

6. Drug target in DNA network
No.

7. Drug-like compound
No.

**Comment by allysonlister** [comment]
Thanks @Drosophilic 

WRT ensuring the annotation is preserved, I can list all records with each UDT prior to the DRAO update, and after the update I will make sure the annotation has been retained. In the past, @knirirr's scripts have been successful with this, but me double checking is a good idea.

1. Adverse outcome pathways: in the COVID-19-tagged Comparative Toxicogenomics Database (CTD, https://fairsharing.org/FAIRsharing.h3tjtr), but this is the only record this tag appears in. Therefore it makes sense to leave it as a UDT, do you agree?

2. Approved drug is in [11 records](https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=&expanded_onto_disciplines=&user_defined_tags=Approved+drug&record_id=&miriam_id=&search_state=visible), but none of the 11 are tagged with COVID-19. Can still add to DRAO if you agree.

3. Coronavirus - I have replaced with COVID-19 and removed this tag. 

4. Drug Target: There are [25 records](https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=&expanded_onto_disciplines=&user_defined_tags=drug+target&record_id=&miriam_id=&search_state=visible) with this tag, but none have the COVID-19 tag, so happy to leave this as a UDT if that remains your preference

5. Drug repositioning is in 1 COVID-19-tagged record (CIDO, https://fairsharing.org/bsg-s001471/).

6. Drug target in DNA network - only in 2 records, not COVID-19 related. Agree with keeping it as a UDT.

7. Drug-like compound - only in 1 record, not COVID-19 related. Agree with keeping it as a UDT.


I am happy to go through each of the COVID-19-tagged records and add any of the UDTs above that you think might be appropriate, though this may take some time. If you'd like me to do this, then should I just focus on the UDTs that you confirm I should promote to DRAO?

**Comment by allysonlister** [comment]
Add approved drug only, after discussion with @Drosophilic and @delphinedauga

**Comment by allysonlister** [comment]
All associated tickets have been resolved. Closing this one.
