### ISSUE TITLE
Drug repositioning

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#55]
'Drug repositioning' is one of the UDTs that will be promoted to DRAO as part of the COVID-19 work. It is in 2 FAIRsharing records, 1 of which is a COVID-19-tagged record (CIDO, https://fairsharing.org/bsg-s001471/).

OMIT https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0027237 does have this term, but no definition - we could add one if required.

_Originally posted by @allysonlister in https://github.com/FAIRsharing/domain-ontology/issues/53#issuecomment-620400886_

**Comment by allysonlister** [comment]
### Definition
The original [MESH term](https://meshb.nlm.nih.gov/record/ui?ui=D058492) used to create the OMIT class does have a definition (listed as a "scope note" in the record): "The deliberate and methodical practice of finding new applications for existing drugs." 

### Hierarchy
The MESH hierarchy lists this class as a child term of Drug Development, which we have as a subject in SRAO (with a sibling class of Drug Discovery). I can see Drug Repositioning as a child of Drug Development, but would like your opinion before we move it out of the DRAO ticket system and into SRAO. Within DRAO, we'd probably want to put it somewhere in the 'planned process' hierarchy, but I don't have a clear idea of where it would make sense to put it:
![plannedprocess](https://user-images.githubusercontent.com/143586/81398158-97cd0c00-9120-11ea-8ba5-d98bad710314.png)

### IRI
It also has an "RDF Unique Identifier" of http://id.nlm.nih.gov/mesh/D058492 that we could use as the class IRI if you agree. Otherwise, we can make use of the OMIT IRI used for the MESH term, which is what we've done in the past: http://purl.obolibrary.org/obo/OMIT_0027237

**Comment by Drosophilic** [comment]
Having Drug Repositioning as a child of Drug Development makes sense.

I don't see the benefit of the RDF Unique Identifier over the OMIT IRI. Why would one choose one over the other?

**Comment by allysonlister** [comment]
The only benefit would be that we are using MeSH's own system of identification, but as I only recently found out about them, all other MeSH terms in DRAO have come through OMIT, and therefore have OMIT IDs. I suggest that we retain this method and use the OMIT IRI. :) Thanks!!

**Comment by delphinedauga** [comment]
I don't completely agree with the fact that it could be a child if 'Drug Development'. The definition of Drug Development is: 'The process of bringing a new drug to market once a lead compounds has been identified through drug discovery'. Here we talk about a new drug where 'drug repositioning' concerns an existing drug. I would put it as the same level as 'Drug Development'.

**Comment by Drosophilic** [comment]
That's a good point @delphinedauga, and I'm now inclined to agree with you.

**Comment by allysonlister** [comment]
Thanks you two! Sounds like 'Drug Repositioning' is heading to SRAO, as a sibling class of 'Drug Development'. I'll make that ticket and transfer this across. Then we can continue the work there.
