### ISSUE TITLE
Approved Drug

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#56]
Approved drug is in [11 records](https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=&expanded_onto_disciplines=&user_defined_tags=Approved+drug&record_id=&miriam_id=&search_state=visible), but none of the 11 are tagged with COVID-19. @Drosophilic has agreed we should promote this as part of the COVID-19 work.

_Originally posted by @allysonlister in https://github.com/FAIRsharing/domain-ontology/issues/53#issuecomment-620400886_

**Comment by allysonlister** [comment]
### Definition
I suggest the [wikipedia definition](https://en.wikipedia.org/wiki/Approved_drug), as it is clear, and there aren't many suitable alternatives after a bit of a wider search: "An approved drug is a preparation that has been validated for a therapeutic use by a ruling authority of a government."

### Hierarchy

We already have 'drug' and 'fda approved drug'. 'Approved drug' is a more generic form of 'fda approved drug, and can be placed within that hierarchy. I suggest we put it as a child of 'clinical drug role', and have 'FDA approved drug' as a child of 'Approved drug'.

![fda](https://user-images.githubusercontent.com/143586/81399017-3c038280-9122-11ea-846d-6a8be5de4d18.png)

Please note that the hierarchy image above shows the "native" label for the terms, but the 'FAIRsharing approved term' (this is the primary label displayed within FAIRsharing) is what would expect, e.g. 'FDA approved drug' instead of 'FDA approved drug role'.

### IRI
I cannot find a suitable IRI in our normal locations (OLS, BioPortal), so I suggest we mint a new IRI.

**Comment by Drosophilic** [comment]
Sounds good, thanks!

**Comment by delphinedauga** [comment]
I agree !

**Comment by allysonlister** [comment]
Perfect! I'll add it to the ontology and close the ticket once it's done.

**Comment by allysonlister** [comment]
New IRI for Approved drug is http://www.fairsharing.org/ontology/DRAO_0000322

**Comment by allysonlister** [comment]
All changes have been made for this ticket, and I've now added the mapping from UDT->DRAO to `development/refactored-IRIs-current.txt`. This ticket is now complete.
