### ISSUE TITLE
Infectology / infectious disease

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#57]
Hi Ally, I can confirm we said 'Infectious Disease Medicine' for the SRAO term, and then we chose 'Infectology' for DRAO.

_Originally posted by @Drosophilic in https://github.com/FAIRsharing/subject-ontology/issues/49#issuecomment-626703517_

**Comment by allysonlister** [comment]
### Label
**Recommendation**: infectious disease

**Reasoning**: https://github.com/FAIRsharing/subject-ontology/issues/49 states that we agreed on Infectology, but I'm starting to think this doesn't sound appropriate for DRAO. I'd like to follow other DRAO classes such as 'cardiovascular disease' and call this class 'infectious disease', which still remains sufficiently different from the SRAO term 'Infectious Disease Medicine' as described in https://github.com/FAIRsharing/subject-ontology/issues/49#issuecomment-626703517. What are your thoughts?

### IRI
**Recommendation**: [EFO](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005741): http://www.ebi.ac.uk/efo/EFO_0005741
 
**Reasoning**: EFO, OBI and IDO have infectious disease as a child term of disease; IDO uses the OGMS disease term (as we do) and OBI and EFO each use their own IRI for their disease term, but the structure is the same. Although all classes would be appropriate, as we are already using many EFO terms for various children of the disease class, and  [EFO has the best definition and equivalentTo cross references to other ontologies](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005741), I would go with EFO.

### Definition
Use EFO's: A disorder resulting from the presence and activity of a microbial, viral, or parasitic agent. It can be transmitted by direct or indirect contact.

### Hierarchy
**Recommendation**: child of disease

**Reasoning**: We already have 'Infection' from OBI ("the detrimental process in which an infectious agent colonizes or replicates in a host environment") as part of the process hierarchy in DRAO, however this is a process and not the 'disease' hierarchy we were talking about earlier in https://github.com/FAIRsharing/subject-ontology/issues/49. Therefore I think we're justified in having this new term for the concept of the diseases (which are classed in DRAO within the disposition hierarchy):
![disposition](https://user-images.githubusercontent.com/143586/82449657-74e91300-9aa3-11ea-9620-73dae92e1b8f.png)

(@Drosophilic thought about perhaps having this as a child of disease -> human disease, but as infectious diseases are broader than just humans, placing it as a child of disease might be more suitable.)

What do you think, @Drosophilic and @delphinedauga? Thanks!

**Comment by delphinedauga** [comment]
Agree !

**Comment by Drosophilic** [comment]
Agreed!

**Comment by allysonlister** [comment]
Please note that this is a completely new term, and therefore will not need a mapping added at development/refactored-IRIs-current.txt
