### ISSUE TITLE
Biocuration

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#6]
A user (https://fairsharing.org/biodbcore-000379/) has requested biocuration, which makes sense to me. We could make it a child of Data Management (ERO, see https://www.ebi.ac.uk/ols/ontologies/ero/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FERO_0001218) as we already have the data management parent class, Data transformation (from OBI).

There does not seem to be an existing IRI for this in OLS, so we may have to mint our own.

**Comment by allysonlister** [comment]
We also already have digital curation from OBI in DRAO as a child of planned process -> documenting. I think this all depends on the perspective we have, as Data management above has also been placed within the OBI hierarchy. I feel that it is best placed within documenting, after having had a closer look at the OBI hierarchy. Opinions, @Drosophilic ? :)

**Comment by Drosophilic** [comment]
After discussion, we have decided to do the following:
Data Management
--> Digital Curation
----> Biocuration

I will ask other members of the ISB exec board for a Biocuration definition.

**Comment by allysonlister** [comment]
Please note that this involves moving digital curation from its current place as a child of documenting and moving it to its new location for the purposes of our application ontology.

**Comment by Drosophilic** [comment]
Definition for Biocuration (from the ISB exec board):
'Biocuration is the extraction of knowledge from unstructured biological and biomedical data into a standard, structured, computable form.' - pm20180910 & International Society for Biocuration. DOI: 10.1371/journal.pbio.2002846

**Comment by allysonlister** [comment]
thanks - will add it now :)

**Comment by Drosophilic** [comment]
I'm not sure we're using this term correctly. Should it be applied to almost all life science databases?

**Comment by allysonlister** [comment]
Some biological databases are curated manually (SwissProt) and others are automatically curated (TrEMBL). To me, I would expect that biocuration is used for those databases that have some aspect of manual curation. However, our current definition does not bear this out, but it is what I was thinking of when we created the term. Perhaps we should make the definition more narrow?

**Comment by Drosophilic** [comment]
I understand biocuration to be both semi-automatic and manual, so I would say we are OK to keep it as is and to also keep it for those databases that have automatic curation.

**Comment by allysonlister** [comment]
Great - happy to close this now if you are?
