### ISSUE TITLE
Modification: Infection to be made visible to FAIRsharing users

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#72]
### What are you changing?
Add the `inSubset=FAIRsharing` annotation property to http://purl.obolibrary.org/obo/IDO_0000586 (Infection). 

### Why are you suggesting this change?

It is currently being used to curate records in FAIRsharing, and therefore needs to have this property set.

### Mapping
No changes will need to be made to the hierarchy, IRIs or to any other properties of the class.

**Comment by allysonlister** [comment]
As shown by the robot diff below, the modifications made to DRAO are only those mentioned in this ticket:
# Ontology comparison

## Left
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/DRAO-merged.owl`

## Right
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/build/DRAO-merged.owl`

### Ontology imports 



### Ontology annotations 


### infection `http://purl.obolibrary.org/obo/IDO_0000586`

#### Added
- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [inSubset](http://www.geneontology.org/formats/oboInOwl#inSubset) "FAIRsharing"@en 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [FAIRsharing alternative term](http://www.fairsharing.org/ontology/domain/DRAO_0000001) "Infection"@en

**Comment by allysonlister** [comment]
### Why am I revisiting Infection?

There is a twist here - I didn't realize, due to the way the original OBI label is, that we had Infection in two places in DRAO:

* http://purl.obolibrary.org/obo/IDO_0000586 (See above), and 
* http://purl.obolibrary.org/obo/OBI_1110021

It is the OBI term that was visible prior to this ticket being made. Therefore we need to decide which term and hierarchy to retain, and update DRAO to reflect that. After this point, we need to tidy up https://fairsharing.org/collection/COVID19Resources, which is the only record in FAIRsharing with this problem.

Below are the two locations (highlighted) of the two infection terms in the current DRAO hierarchy.

![infection](https://user-images.githubusercontent.com/143586/106921719-2e584900-6704-11eb-88c9-90b802a7c20a.png)

### Why are you suggesting this change?

As this is an automatically-generated hierarchy, it is inevitable that these kinds of concept duplications will occur, and should be resolved as they are discovered.

### Mapping

I suggest the following:

* Retain the OBI class, which is the one that has been visible thus far.
* Move the child of IDO_0000586 (which is http://purl.obolibrary.org/obo/OBI_1110021, hospital-acquired infection / nosocomial infection) to be a child of http://purl.obolibrary.org/obo/OBI_1110021
* The IDO class will need its in_fairsharing flag removed and removed completely from DRAO.

Old IRI | New IRI | Note
------------ | ------------- | -------------
http://purl.obolibrary.org/obo/IDO_0000586 | http://purl.obolibrary.org/obo/OBI_1110021 | The IDO term is not required, as we already have an OBI equivalent already in use.

### Hierarchy
**Recommendation**: I suggest that we align with OBI, and put the child of IDO _Infection_ under the OBI _Infection_

**Reasoning**: I prefer the placement of the OBI term.

Please could @delphinedauga and @Drosophilic provide comments / confirm they're happy with these suggested changes. Thanks!

**Comment by delphinedauga** [comment]
Thanks @allysonlister , I agree with your suggestion :)

**Comment by Drosophilic** [comment]
I agree @allysonlister, all sounds good!

**Comment by allysonlister** [comment]
Updates to DRAO have resulted in the following changes, consistent with the work required for this ticket.

# Ontology comparison

## Left
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/DRAO-merged.owl`

## Right
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/build/DRAO-merged.owl`

### Ontology imports 



### Ontology annotations 


### hospital-acquired infection `http://purl.obolibrary.org/obo/IDO_0000630`
#### Removed
- [hospital-acquired infection](http://purl.obolibrary.org/obo/IDO_0000630) SubClassOf [infection](http://purl.obolibrary.org/obo/IDO_0000586) 

#### Added
- [hospital-acquired infection](http://purl.obolibrary.org/obo/IDO_0000630) SubClassOf [infection process](http://purl.obolibrary.org/obo/OBI_1110021) 


### infection `http://purl.obolibrary.org/obo/IDO_0000586`
#### Removed
- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A part of an extended organism that itself has as part a population of one or more infectious agents and that (1) exists as a result of processes initiated by members of the infectious agent population and is (2) clinically abnormal in virtue of the presence of this infectious agent population, or (3) has a disposition to bring clinical abnormality to immunocompetent organisms of the same Species as the host (the organism corresponding to the extended organism) through transmission of a member or offspring of a member of the infectious agent population."@en 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [imported from](http://purl.obolibrary.org/obo/IAO_0000412) [ido.owl](http://purl.obolibrary.org/obo/ido.owl) 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [inSubset](http://www.geneontology.org/formats/oboInOwl#inSubset) "FAIRsharing"@en 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [label](http://www.w3.org/2000/01/rdf-schema#label) "infection"@en 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) [FAIRsharing alternative term](http://www.fairsharing.org/ontology/domain/DRAO_0000001) "Infection"@en 

- Class: [infection](http://purl.obolibrary.org/obo/IDO_0000586) 

- [infection](http://purl.obolibrary.org/obo/IDO_0000586) SubClassOf [material_entity](http://purl.obolibrary.org/obo/BFO_0000040)
