### ISSUE TITLE
Refactor EDAM Protocol and OBI Protocol

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/domain-ontology#77]
When moving the children of the EDAM _Report_ class, I noticed that we have both EDAM _Protocol_ and OBI _Protocol_. I'll find out how many of each are in FAIRsharing before I recommend which we keep, but at the moment I think keeping the OBI term would be better due to its richer hierarchy within DRAO.

_Originally posted by @allysonlister in https://github.com/FAIRsharing/domain-ontology/issues/71#issuecomment-773431894_

**Comment by allysonlister** [comment]
@ramGranell has kindly let me know that 73 records have the EDAM term http://edamontology.org/data_2531, and 16 have http://purl.obolibrary.org/obo/OBI_0000272.

I am happy to write up the change more formally, but which class would you like to keep @delphinedauga and @Drosophilic?

I'd probably still suggest retaining the OBI term. Thanks!

**Comment by Drosophilic** [comment]
Hi @allysonlister - I vote for the EDAM term as it (to my mind) a better definition. The OBI term definition seems less clear.

**Comment by delphinedauga** [comment]
Hi both !
-> I like the Edam definition but the concept of reproducibility is missing (contrary to the OBI def) (Edam has also a small error in the def, about is duplicated "collection of information about about how a scientific ". Is there a way to notify them of this typing error?)
-> Not really comfortable with the child_of "report" (Edam), as a report implies that the action (experiment) should have been done before, which is the contrary of a protocol. The definition of "plan specification" from OBI is more adapted.
-> For these reasons, I prefer the OBI definition

**Comment by allysonlister** [comment]
@delphinedauga and @Drosophilic and I have spoken about this and decided to go with OBI Protocol. The following is a summary of our discussion.

### Why Refactor Protocol

While working on #71 we realized that Protocol was present twice.

* http://edamontology.org/data_2531
* http://purl.obolibrary.org/obo/OBI_0000272

Both terms are visible in FAIRsharing. 

Below are the two locations (highlighted) of the two infection terms in the current DRAO hierarchy.
![protocol](https://user-images.githubusercontent.com/143586/107088120-617a0580-67f4-11eb-858c-8b5eebd1f71d.png)


### Why are you suggesting this change?

As this is an automatically-generated hierarchy, it is inevitable that these kinds of concept duplications will occur, and should be resolved as they are discovered.

### Mapping

We have agreed to the following:

* Retain the OBI class. 
* Delete the EDAM class. There are no children of this class to refactor.
* The IDO class will need its in_fairsharing flag removed and removed completely from DRAO.

Old IRI | New IRI | Note
------------ | ------------- | -------------
http://edamontology.org/data_2531 | http://purl.obolibrary.org/obo/OBI_0000272 | The EDAM term is not required, as we already have an OBI equivalent already in use.

### Hierarchy
**Decision**: Align with OBI.

**Reasoning**:  The EDAM definition is good, but the concept of reproducibility is missing (contrary to the OBI def). The position of the OBI protocol as a child of "plan specification" is preferred.

I'll move ahead with these changes.

**Comment by allysonlister** [comment]
The updates I've just performed show the following changes. Please note _Report_ is mentioned because I noticed with this update that I had accidentally retained one outstanding annotation request within `development/DRAO-ontofox-annotation.txt`, which I have now fixed (#71 please take note).

# Ontology comparison

## Left
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/DRAO-merged.owl`

## Right
- Ontology IRI: `http://www.fairsharing.org/ontology/domain/DRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/development/build/DRAO-merged.owl`

### Ontology imports 



### Ontology annotations 



### Gene report `http://edamontology.org/data_0916`
#### Removed
- [Gene report](http://edamontology.org/data_0916) SubClassOf [data_2048](http://edamontology.org/data_2048) 

#### Added
- [Gene report](http://edamontology.org/data_0916) SubClassOf [report](http://purl.obolibrary.org/obo/IAO_0000088) 


### Protocol `http://edamontology.org/data_2531`
#### Removed
- [Protocol](http://edamontology.org/data_2531) [替代术语](http://purl.obolibrary.org/obo/IAO_0000118) "Experiment metadata" 

- [Protocol](http://edamontology.org/data_2531) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A human-readable collection of information about about how a scientific experiment or analysis was carried out that results in a specific set of data or results used for further analysis or to test a specific hypothesis." 

- [Protocol](http://edamontology.org/data_2531) [替代术语](http://purl.obolibrary.org/obo/IAO_0000118) "Experiment report" 

- [Protocol](http://edamontology.org/data_2531) [imported from](http://purl.obolibrary.org/obo/IAO_0000412) [EDAM.owl](http://edamontology.org/EDAM.owl) 

- [Protocol](http://edamontology.org/data_2531) [inSubset](http://www.geneontology.org/formats/oboInOwl#inSubset) "FAIRsharing"@en 

- [Protocol](http://edamontology.org/data_2531) [替代术语](http://purl.obolibrary.org/obo/IAO_0000118) "Experiment annotation" 

- [Protocol](http://edamontology.org/data_2531) [label](http://www.w3.org/2000/01/rdf-schema#label) "Protocol" 

- [Protocol](http://edamontology.org/data_2531) [FAIRsharing alternative term](http://www.fairsharing.org/ontology/domain/DRAO_0000001) "Experiment metadata"@en 

- Class: [Protocol](http://edamontology.org/data_2531) 

- [Protocol](http://edamontology.org/data_2531) SubClassOf [report](http://purl.obolibrary.org/obo/IAO_0000088) 


### data_2048 `http://edamontology.org/data_2048`
#### Removed
- Class: [data_2048](http://edamontology.org/data_2048)

**Comment by allysonlister** [comment]
All curation has been performed within FAIRsharing to use the OBI term instead.

**Comment by allysonlister** [comment]
@delphinedauga has checked this modification.
